[package]
edition = "2021"
name = "ceci"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
clap = {version = "4.0", features = ["derive", "deprecated"]}
