version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/rust:1.63.0
    steps:
{%- for command in job.steps -%}
{%- match command -%}
{%- when Command::Shell { title, command } %}
      - run:
          name: {{title}}
          command: {{command}}
{% when Command::Checkout %}
      - checkout
{% when Command::RestoreCache { key_files } %}
      - restore_cache:
          keys:
            - {{job.ecosystem}}{%- for file in key_files -%}
            -{{ "{{ checksum \""}}{{file}}{{"\" }}" }}
            {%- endfor -%}
            - {{job.ecosystem}}
{% when Command::StoreCache { key_files, data_paths } %}
      - save_cache:
          keys:
            - {{job.ecosystem}}{%- for file in key_files -%}
            -{{ "{{ checksum \""}}{{file}}{{"\" }}" }}
            {%- endfor -%}
            - {{job.ecosystem}}
          paths:
{%- for data_path in data_paths -%}
            - {{data_path}}
{%- endfor %}
{% when Command::StoreTestResults { paths } %}
{%- for path in paths %}
      - store_test_results:
          path: {{path}}
{%- endfor %}
{% else %}
      WOOPS: unmatched command
{% endmatch -%}
{%- endfor %}

      - run: otel-cli exec --service cargo --name "cargo check" -- cargo check --workspace

      - run:
          name: install cargo-nextest
          command: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - run:
          name: install circleci-junit-fix
          command: curl -sSL https://github.com/conradludgate/circleci-junit-fix/releases/download/v0.2.0/circleci-junit-fix-v0.2.0-x86_64-unknown-linux-gnu.tar.gz | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - run: otel-cli exec --service cargo --name "cargo nextest" -- cargo nextest run --workspace --profile ci
      - run: otel-cli exec --service cargo --name "cargo test" -- cargo test --workspace --doc
      - run: otel-cli exec --service cargo --name "cargo build" -- cargo build --workspace

      - run:
          name: fix junit XML
          command: cat target/nextest/ci/junit.xml | circleci-junit-fix > fixed-report.xml
      - store_test_results:
          path: fixed-report.xml
